echo There are $# arguments to $0: $*
echo first argument: $1
cd ~/documents/mynodecode
mkdir $1
cd $1
npm init -y
npm i -D babel-cli babel-preset-es2015 nodemon
npm install express --save
echo "{'presets':['es2015']}" > .babelrc
git init
echo "
# OS X
.DS_Store*
Icon?
._*


db.js

# Logs
logs
*.log
npm-debug.log*

# Runtime data
pids
*.pid
*.seed


# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# node-waf configuration
.lock-wscript

# Compiled binary addons (http://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules
jspm_packages

# Optional npm cache directory
.npm

# Optional REPL history
.node_repl_history" > .gitignore

mkdir src
cd src
echo "import express from 'express';
let app = express();
app.get('/', (req, res) => {
  res.send('Welcome');
});
app.listen(3000);" > index.js


echo "cd ~/documents/mynodecode/$1"
echo "npm run dev"
echo " "
sed -i '' $'s|"\\\,"|"repository": \\\{"type": "git","url": "git://github.com/wolfeidau/npmtest.git"\\},' ~/documents/mynodecode/$1/package.json
sed -i '' $'s|"test":|"dev":"babel-node src/index.js"\\\n"test":|g' ~/documents/mynodecode/$1/package.json
